-- =============================================================================
-- 07_create_fact_tables.sql
-- Synthetic manufacturing layer — the three fact tables
--
-- CORE PRINCIPLE: these tables hold RAW EVENTS ONLY. Planned and actual
-- quantities, scheduled and actual times, good and scrap units, downtime
-- intervals, inspection outcomes. There is NO yield %, NO waste rate, NO OEE
-- column anywhere in this schema. Every KPI derives in SQL, and OEE must
-- reconcile from Availability x Performance x Quality.
--
-- If a metric could be stored here, it is not stored here. That is the point.
--
-- -----------------------------------------------------------------------------
-- THE TWO COLUMNS THAT DO NOT EXIST IN A REAL PLANT
-- -----------------------------------------------------------------------------
-- fact_downtime.true_reason_code and fact_downtime.was_logged are the
-- instrument, not the data.
--
-- In a real MES you have ONE reason code — whatever the operator pressed — and
-- you have NO record of the stops nobody entered. That is exactly the problem:
-- the distortion is invisible from inside the data.
--
-- Because this layer is synthetic, the generator knows the truth and writes it
-- alongside the report. KPI views read ONLY `reported_reason_code`, and ONLY
-- rows where `was_logged = TRUE`, because that is all a real analyst would
-- have. The data-quality views read everything and measure the gap.
--
-- This is not giving myself information an analyst wouldn't have. It is
-- building a ruler so the distortion can be MEASURED rather than asserted.
--
-- IMPORTANT: set query processing location to EU before running.
-- =============================================================================


-- =============================================================================
-- fact_production_batch — one row per batch run
-- =============================================================================
CREATE OR REPLACE TABLE `bakery_synthetic.fact_production_batch` (
  batch_id                   STRING    NOT NULL,
  production_date            DATE      NOT NULL,
  product_id                 INT64     NOT NULL,   -- FK dim_product
  machine_id                 INT64     NOT NULL,   -- FK dim_machine (must agree with dim_product)

  -- -- The plan ---------------------------------------------------------------
  planned_units              INT64     NOT NULL,
  loads_used                 FLOAT64   NOT NULL,   -- decks or trays consumed, fractional
  scheduled_start_ts         TIMESTAMP NOT NULL,
  scheduled_end_ts           TIMESTAMP NOT NULL,

  -- PLANNED PRODUCTION TIME — the denominator of OEE Availability.
  -- This is SCHEDULED BATCH TIME, not shift length. A batch that was allocated
  -- 40 minutes and lost 8 to a breakdown ran at 80% availability. Using shift
  -- length here would make Availability a measure of how idle the plant was,
  -- which is not what the metric is for.
  planned_production_minutes FLOAT64   NOT NULL,

  -- -- What happened ----------------------------------------------------------
  actual_start_ts            TIMESTAMP NOT NULL,
  actual_end_ts              TIMESTAMP NOT NULL,

  -- Time the machine was actually running. Stop time is NOT stored here — it
  -- lives as intervals in fact_downtime and is summed in SQL. Storing both
  -- would let them drift.
  run_time_minutes           FLOAT64   NOT NULL,

  -- -- Output -----------------------------------------------------------------
  -- total_units_produced is NOT stored. It is good_units + scrap_units, and
  -- storing a derivable sum invites it to disagree with its own parts.
  good_units                 INT64     NOT NULL,
  scrap_units                INT64     NOT NULL
)
PARTITION BY production_date
CLUSTER BY machine_id, product_id
OPTIONS (
  description =
    'SYNTHETIC. One row per production batch. Raw events only — no yield, waste '
    'or OEE columns; every KPI derives in SQL. planned_production_minutes is '
    'scheduled BATCH time, not shift length: it is the denominator of OEE '
    'Availability. Generated by scripts/generate_synthetic_production.py from '
    'config/synthetic_generator.yaml. Produces no findings by construction.'
);


-- =============================================================================
-- fact_downtime — one row per stop, including the ones nobody logged
-- =============================================================================
CREATE OR REPLACE TABLE `bakery_synthetic.fact_downtime` (
  downtime_id            STRING    NOT NULL,
  batch_id               STRING    NOT NULL,   -- FK fact_production_batch
  machine_id             INT64     NOT NULL,   -- FK dim_machine
  production_date        DATE      NOT NULL,

  start_ts               TIMESTAMP NOT NULL,
  end_ts                 TIMESTAMP NOT NULL,
  duration_minutes       FLOAT64   NOT NULL,

  -- WHAT THE OPERATOR PRESSED. This is the only reason code a real analyst has.
  -- May be '99' (Other) even when the true cause was a changeover or a short
  -- mechanical stop — because "Other" is the fastest button on the terminal and
  -- the operator has dough on their hands.
  reported_reason_code   STRING    NOT NULL,
  reported_reason_label  STRING    NOT NULL,

  -- WHAT ACTUALLY HAPPENED. Does not exist in a real MES. Written here so the
  -- data-quality check can MEASURE the miscoding rather than assert it.
  true_reason_code       STRING    NOT NULL,
  true_reason_label      STRING    NOT NULL,

  -- FALSE = a micro-stop that never made it onto the terminal at all.
  -- These rows are invisible to the KPI views, which is the point: unlogged
  -- stops silently INFLATE Availability, and from inside real data you cannot
  -- tell. This is the harder half of the pathology.
  was_logged             BOOL      NOT NULL
)
PARTITION BY production_date
CLUSTER BY machine_id, reported_reason_code
OPTIONS (
  description =
    'SYNTHETIC. One row per production stop. reported_reason_code is what the '
    'operator entered — the only code a real analyst would have. '
    'true_reason_code and was_logged do NOT exist in a real MES; they are the '
    'instrument that lets the data-quality views measure miscoding and unlogged '
    'micro-stops. KPI views must read reported_reason_code WHERE was_logged.'
);


-- =============================================================================
-- fact_quality_inspection — sampled, not census
-- =============================================================================
CREATE OR REPLACE TABLE `bakery_synthetic.fact_quality_inspection` (
  inspection_id     STRING    NOT NULL,
  batch_id          STRING    NOT NULL,   -- FK fact_production_batch
  production_date   DATE      NOT NULL,
  inspection_ts     TIMESTAMP NOT NULL,

  -- A real line inspects a fraction of batches, not every one. Sampling is why
  -- the inspection table is NOT the source of the Quality term in OEE — that
  -- comes from good_units / (good + scrap) on every batch. Inspections are a
  -- separate signal about whether defects were CAUGHT, not about how many
  -- there were.
  sample_size       INT64     NOT NULL,
  defects_found     INT64     NOT NULL,
  outcome           STRING    NOT NULL,   -- PASS | FAIL
  defect_type       STRING                -- NULL when outcome = PASS
)
PARTITION BY production_date
CLUSTER BY outcome
OPTIONS (
  description =
    'SYNTHETIC. Sampled quality inspections — a fraction of batches, not all. '
    'This table does NOT feed the Quality term of OEE (that derives from '
    'good/scrap units on every batch). It is a separate signal about whether '
    'defects were caught.'
);


-- =============================================================================
-- Structural validation — the tables exist and are empty, ready for load
-- =============================================================================
ASSERT (
  SELECT COUNT(*) FROM `bakery_synthetic.INFORMATION_SCHEMA.TABLES`
  WHERE table_name IN (
    'dim_product', 'dim_machine',
    'fact_production_batch', 'fact_downtime', 'fact_quality_inspection'
  )
) = 5
  AS 'Validation failed: the five-table star schema is not complete.';

SELECT table_name, table_type
FROM `bakery_synthetic.INFORMATION_SCHEMA.TABLES`
ORDER BY table_name;
